# Generated by Django 5.0.1 on 2024-01-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.TextField(max_length=500, verbose_name='プロフィール'),
        ),
    ]
