# Generated by Django 5.0.1 on 2024-01-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_words_misstake_delete_wards'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='yaku',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
