# Generated by Django 5.0.1 on 2024-01-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_words_ex_1_yaku_words_ex_2_yaku_words_ex_3_yaku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='ex_2',
        ),
        migrations.RemoveField(
            model_name='words',
            name='ex_2_yaku',
        ),
        migrations.RemoveField(
            model_name='words',
            name='ex_3',
        ),
        migrations.RemoveField(
            model_name='words',
            name='ex_3_yaku',
        ),
    ]
