# Generated by Django 5.0.1 on 2024-02-03 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_words_ex_2_remove_words_ex_2_yaku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='ex_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='words',
            name='ex_1_yaku',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='WordsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product_image/')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words_image', to='main.words')),
            ],
        ),
    ]
