# Generated by Django 5.0.1 on 2024-02-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_words_ex_1_alter_words_ex_1_yaku_wordsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordsimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='word_image/'),
        ),
    ]
